// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Byte Cats",
            "url": "https://github.com/Byte-Cats/microman"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/Byte-Cats/microman/blob/main/LICENCE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Redirects the client from the root path to /docs with a 303 See Other.",
                "tags": [
                    "general"
                ],
                "summary": "Redirect to docs",
                "responses": {
                    "303": {
                        "description": "redirect to /docs",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/add": {
            "post": {
                "description": "Creates a new row in the items table (see data/schema.sql) from a JSON body and returns the created item, including its generated id. Real MySQL-backed CRUD via the data package, demonstrating database wiring rather than a stub response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rest"
                ],
                "summary": "Add an item",
                "parameters": [
                    {
                        "description": "Item to create",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/data.Item"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delete": {
            "delete": {
                "description": "Deletes the row in the items table (see data/schema.sql) identified by the ` + "`" + `id` + "`" + ` query parameter and confirms deletion as JSON. Real MySQL-backed CRUD via the data package, demonstrating database wiring rather than a stub response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rest"
                ],
                "summary": "Delete an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "missing or invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/docs": {
            "get": {
                "description": "Writes a fixed \"Docs\" string. Real interactive API docs are served separately by the Swagger UI mounted at /swagger/.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Docs placeholder",
                "responses": {
                    "200": {
                        "description": "Docs",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/edit": {
            "put": {
                "description": "Updates the name/value of the row in the items table (see data/schema.sql) identified by the ` + "`" + `id` + "`" + ` query parameter, from a JSON body, and returns the updated item. Real MySQL-backed CRUD via the data package, demonstrating database wiring rather than a stub response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rest"
                ],
                "summary": "Edit an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data.Item"
                        }
                    },
                    "400": {
                        "description": "missing/invalid id or request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get": {
            "get": {
                "description": "Fetches a single row from the items table (see data/schema.sql) by its id, passed as the ` + "`" + `id` + "`" + ` query parameter, and returns it as JSON. Real MySQL-backed CRUD via the data package, demonstrating database wiring rather than a stub response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rest"
                ],
                "summary": "Get an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data.Item"
                        }
                    },
                    "400": {
                        "description": "missing or invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/home": {
            "get": {
                "description": "Writes a fixed welcome message for the microman API and logs the request.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Home page",
                "responses": {
                    "200": {
                        "description": "welcome message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Writes a fixed informational string describing this endpoint.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Info page",
                "responses": {
                    "200": {
                        "description": "info string",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data.Item": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "handlers.AddRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "handlers.DeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "handlers.EditRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.420.69",
	Host:             "localhost:6969",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Microman API",
	Description:      "Minimal Go HTTP API starter kit (no web framework) built on net/http and gorilla/mux. Most routes are still stub handlers; see the /docs endpoint and each handler's doc comment for the actual current behavior.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
